# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Utkarsh Gupta
tagline:             'Sexy Tagline'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
gems: [jekyll-paginate]
paginate:            3

# About/contact
author:
  name:              Utkarsh Gupta
  url:               https://twitter.com/UtkarshGpta
  email:             utkarshgpta@gmail.com

# Custom vars
version:             1.0.0
